name: Install Nix and setup cache
inputs:
  nix_conf:
    description: nix_conf pass to nixbuild/nix-quick-install-action
    required: false
    default: |
      accept-flake-config = true
      experimental-features = nix-command flakes
      keep-derivations = true
      keep-outputs = true
  key:
    description: Key to actions/cache
    required: false
    default: nix
  use_nixpkgs_in_flake:
    description: Use nixpkgs defined in flake.nix
    required: false
    default: true
  nixpkgs_url:
    description: Nixpkgs URL
    required: false
    default: https://nixos.org/channels/nixos-24.05
  clean:
    description: Clean up disk space
    required: false
    default: false
  debug:
    description: Enable debug
    required: false
    default: false
  debug_token:
    default: ${{ github.token }}
    description: Set github token for gh cli
runs:
  using: composite
  steps:
    - shell: bash
      env:
        CLEAN: ${{ inputs.clean }}
      run: exec ${{ github.action_path }}/prepare.sh
    # nixbuild/nix-quick-install-action only support x86_64 for now
    - uses: nixbuild/nix-quick-install-action@v28
      if: ${{ runner.arch == 'X64' }}
      with:
        nix_conf: ${{ inputs.nix_conf }}
    - uses: cachix/install-nix-action@v27
      if: ${{ runner.arch != 'X64' }}
      with:
        extra_nix_config: ${{ inputs.nix_conf }}
    - name: Nix restore pre
      shell: bash
      env:
        CACHE_KEY: ${{ inputs.key }}
      run: exec ${{ github.action_path }}/restore.sh pre
    - uses: actions/cache/restore@v4
      with:
        key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ runner.arch }}-${{ env.CACHE_TIMESTAMP }}
        restore-keys: |
          ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ runner.arch }}
        path: |
          /nix/store
          /nix/var/nix/db
          /nix/var/nix/gcroots
          /nix/var/nix/profiles
          ~/.cache/nix
          ~/.local/state/nix
    - name: Nix restore post
      shell: bash
      env:
        USE_NIXPKGS_IN_FLAKE: ${{ inputs.use_nixpkgs_in_flake }}
        NIXPKGS_URL: ${{ inputs.nixpkgs_url }}
      run: exec ${{ github.action_path }}/restore.sh post
    - name: Debug
      if: ${{ inputs.debug == true || inputs.debug == 'true' || inputs.debug == 'nopause' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.debug_token }}
      run: exec ${{ github.action_path }}/debug.sh "${{ inputs.debug }}"
