name: Install Nix and setup cache (post actions)
runs:
  using: composite
  steps:
    - name: Nix save pre
      shell: bash
      run: exec ${{ github.action_path }}/save.sh pre
    - uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      if: ${{ env.CACHE_NEED_UPDATE == 'yes' }}
      with:
        key: ${{ env.CACHE_KEY }}-${{ env.CURRENT_SYSTEM }}-${{ env.CACHE_TIMESTAMP }}
        path: |
          /nix/store
          /nix/var/nix/db
          /nix/var/nix/gcroots
          /nix/var/nix/profiles
          ~/.cache/nix
          ~/.local/state/nix
          ~/.nix-channels
          ~/.nix-defexpr
