name: Install Nix and setup cache (post actions)
runs:
  using: composite
  steps:
    - shell: bash
      run: exec ${{ github.action_path }}/save.sh pre
    - uses: actions/cache/save@v4
      if: ${{ env.CACHE_NEED_UPDATE == 'yes' }}
      with:
        key: ${{ env.CACHE_KEY }}-${{ runner.os }}-${{ runner.arch }}-${{ env.CACHE_TIMESTAMP }}
        path: |
          /nix/store
          /nix/var/nix/db/db.sqlite
          /nix/var/nix/gcroots
          /nix/var/nix/profiles
          ~/.cache/nix
          ~/.local/state/nix
