name: Nix
permissions: {}
concurrency:
  # Concurrency is not possible because of clear_cache and nix_with_cache
  group: nix
on:
  pull_request:
    paths:
      - 'nix/**'
      - .github/workflows/nix.yml
  push:
    # Only include top-level branches, ignore branches like dependabot/*
    branches:
      - '*'
    paths:
      - 'nix/**'
      - .github/workflows/nix.yml
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debug
        type: boolean
        default: false
      os:
        description: OS to run
        type: choice
        options: 
          - linux
          - darwin
          - aarch64-linux
          - x86_64-linux
          - aarch64-darwin
          - x86_64-darwin
          - all
        default: all
      install_action:
        description: Install action to use
        type: choice
        options: 
          - cachix
          - nixbuild
          - all
        default: nixbuild
      btrfs:
        description: Enable BTRFS RAID0 on Linux
        type: boolean
        default: false
      clean:
        description: Clean for max disk space
        type: boolean
        default: false
jobs:
  clear_cache:
    if: ${{ ! inputs.debug }}
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh --repo "$GITHUB_REPOSITORY" cache list --key nix- --json id --jq '.[].id' | while read -r id
          do
            gh --repo "$GITHUB_REPOSITORY" cache delete "$id"
          done
  nix:
    needs: clear_cache
    if: ${{ always() && !failure() && !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        system: >-
          ${{ fromJSON(
            inputs.os == 'linux' && '["x86_64-linux", "aarch64-linux"]' || (
            inputs.os == 'darwin' && '["aarch64-darwin", "x86_64-darwin"]' || (
            inputs.os == 'aarch64-linux' && '["aarch64-linux"]' || (
            inputs.os == 'x86_64-linux' && '["x86_64-linux"]' || (
            inputs.os == 'aarch64-darwin' && '["aarch64-darwin"]' || (
            inputs.os == 'x86_64-darwin' && '["x86_64-darwin"]' || (
            '["x86_64-linux", "aarch64-linux", "aarch64-darwin", "x86_64-darwin"]'
          ))))))) }}
        install_action: >-
          ${{ fromJSON(
            inputs.install_action == 'cachix' && '[ "cachix" ]' || (
            inputs.install_action == 'nixbuild' && '[ "nixbuild" ]' || (
            '[ "cachix", "nixbuild" ]'
          ))) }}
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-linux
            os: ubuntu-24.04-arm
          - system: aarch64-darwin
            os: macos-latest
          - system: x86_64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./nix
        with:
          btrfs: ${{ inputs.btrfs }}
          clean: ${{ inputs.clean }}
          debug: ${{ inputs.debug }}
          system: ${{ matrix.system }}
          install_action: ${{ matrix.install_action }}
      - name: Install tools for debug
        run: |
          nix-env -f '<nixpkgs>' -iA cloudflared tmux
      - uses: ./nix/post
  nix_with_cache:
    if: ${{ ! inputs.debug }}
    needs: nix
    strategy:
      fail-fast: false
      matrix:
        system: >-
          ${{ fromJSON(
            inputs.os == 'linux' && '["x86_64-linux", "aarch64-linux"]' || (
            inputs.os == 'darwin' && '["aarch64-darwin", "x86_64-darwin"]' || (
            inputs.os == 'aarch64-linux' && '["aarch64-linux"]' || (
            inputs.os == 'x86_64-linux' && '["x86_64-linux"]' || (
            inputs.os == 'aarch64-darwin' && '["aarch64-darwin"]' || (
            inputs.os == 'x86_64-darwin' && '["x86_64-darwin"]' || (
            '["x86_64-linux", "aarch64-linux", "aarch64-darwin", "x86_64-darwin"]'
          ))))))) }}
        install_action: >-
          ${{ fromJSON(
            inputs.install_action == 'cachix' && '[ "cachix" ]' || (
            inputs.install_action == 'nixbuild' && '[ "nixbuild" ]' || (
            '[ "cachix", "nixbuild" ]'
          ))) }}
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-linux
            os: ubuntu-24.04-arm
          - system: aarch64-darwin
            os: macos-latest
          - system: x86_64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./nix
        with:
          system: ${{ matrix.system }}
          install_action: ${{ matrix.install_action }}
      - name: Install tools for debug
        run: |
          nix-env -f '<nixpkgs>' -iA cloudflared tmux
      - name: Test if restore from cache success
        run: |
          [ -e /nix/store.bak ] && [ ! -e /nix/store.failed ]
      - uses: ./nix/post
      - name: Test if cache does not need update
        run: |
          [ "$CACHE_NEED_UPDATE" != yes ]
  nix_with_clean:
    if: ${{ ! inputs.debug }}
    needs: nix
    strategy:
      fail-fast: false
      matrix:
        system: >-
          ${{ fromJSON(
            inputs.os == 'linux' && '["x86_64-linux", "aarch64-linux"]' || (
            inputs.os == 'darwin' && '["aarch64-darwin", "x86_64-darwin"]' || (
            inputs.os == 'aarch64-linux' && '["aarch64-linux"]' || (
            inputs.os == 'x86_64-linux' && '["x86_64-linux"]' || (
            inputs.os == 'aarch64-darwin' && '["aarch64-darwin"]' || (
            inputs.os == 'x86_64-darwin' && '["x86_64-darwin"]' || (
            '["x86_64-linux", "aarch64-linux", "aarch64-darwin", "x86_64-darwin"]'
          ))))))) }}
        install_action: >-
          ${{ fromJSON(
            inputs.install_action == 'cachix' && '[ "cachix" ]' || (
            inputs.install_action == 'nixbuild' && '[ "nixbuild" ]' || (
            '[ "cachix", "nixbuild" ]'
          ))) }}
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-linux
            os: ubuntu-24.04-arm
          - system: aarch64-darwin
            os: macos-latest
          - system: x86_64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./nix
        with:
          btrfs: true
          clean: true
          system: ${{ matrix.system }}
          install_action: ${{ matrix.install_action }}
